version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: docker-compose down
          command: docker-compose down
  # deploy:
  #   machine:
  #     image: circleci/classic:edge
  #   steps:
  #     - checkout
  #     # see: https://devcenter.heroku.com/articles/container-registry-and-runtime#using-a-ci-cd-platform
  #     - run:
  #         name: "build docker image"
  #         command: docker build --rm=false -t registry.heroku.com/${HEROKU_APP_NAME}/web .
  #     - run:
  #         name: setup heroku command
  #         command: bash .circleci/setup_heroku.sh
  #     - run:
  #         name: heroku maintenance on
  #         command: heroku maintenance:on --app ${HEROKU_APP_NAME}
  #     - run:
  #         # HEROKU_AUTH_TOKEN is generated by `heroku auth:token`
  #         name: "push container to registry.heroku.com"
  #         command: |
  #           echo "$HEROKU_AUTH_TOKEN" | docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
  #           docker push registry.heroku.com/${HEROKU_APP_NAME}/web
  #           bash .circleci/heroku-container-release.sh
  #     - run:
  #         name: heroku maintenance off
  #         command: heroku maintenance:off --app ${HEROKU_APP_NAME}
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: "build docker image"
          command: docker build --rm=false -t registry.heroku.com/${HEROKU_APP_NAME}/web .
      - run:
          name: setup heroku command
          command: bash .circleci/setup_heroku.sh
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
          name: heroku deploy
          command: |
            git pull https://git.heroku.com/${HEROKU_APP_NAME}.git
            git push https://git.heroku.com/${HEROKU_APP_NAME}.git master
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master