version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      # - run:
      #     name: docker-compose down
      #     command: docker-compose down
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # see: https://devcenter.heroku.com/articles/container-registry-and-runtime#using-a-ci-cd-platform
      - run:
          name: "build docker image"
          command: docker build --rm=false -t registry.heroku.com/blog884/web .
      - run:
          name: setup heroku command
          command: bash .circleci/setup_heroku.sh
      # - run:
      #     name: heroku maintenance on
      #     command: heroku maintenance:on --app blog884
      # - run:
      #     # HEROKU_AUTH_TOKEN is generated by `heroku auth:token`
      #     name: "push container to registry.heroku.com"
      #     command: |
      #       docker login --username=_ --password=68f98e9a-066c-4d40-8cd7-9cf797a14a1d registry.heroku.com
      #       docker push registry.heroku.com/blog884/web
      #       bash .circleci/heroku-container-release.sh
      # - run:
      #     name: heroku maintenance off
      #     command: heroku maintenance:off --app blog884
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master